#Config SleepingPlus
# Language of the plugin. (French or English)
language: English
# Do you use the permissions of the plugin?
permissions: false
# Effects when the player becomes tired.
# Identified by name, for how long, in seconds, the rate of fatigue so that the effect is activated.
potionsEffect: SLOW,10,30,2/SLOW_DIGGING,10,40,2/BLINDNESS,10,60,3
# A period to indicate the number of seconds without sleep, the fatigue rate increases by the number below after this time.
timeNoSleep: 20
# The number of minutes it takes being offline for fatigue to be remove by the number below.
timeExitServer: 10
# The number of fatigue that will be added or removed.
nbFatigueRate: 2
# The damage of fatigue when the player has all the potions effect on him. If -1, the option is disable.
damageFatigue: -1
# Number of seconds where you must stay in bed will remove the nbFatigueRate.
timeInBed: 15
# Number of seconds where the player must to stay on a chair will remove the nbFatigueRate.
timeOnChair: 10
# Number of fatigue which will be added at the rate of fatigue in a death.
nbRateWithDeath: 10
# Would you use the xp bar to show the number of fatigue?
useXpBar: false
# Would you want to use the automatic fatigue when you connect on the server?
activateFatigueOnConnect: false
# Activate this and you can go to bed at day
activateBedAtDay: true
# List of world where the plugin should be enable. Create the list like this world:anotherworld . If null, the plugin will be enable in every world.
listworld: null